@startuml
title C4 – Nivel 4 (Código) ms-gestion-suscripciones | Layered Architecture

package "api.rest" {
  class SuscripcionesController
}

package "application.service" {
  class SuscripcionesService
}

package "application.dto" {
  class SuscripcionDto
}

package "application.mapper" {
  class SuscripcionMapper
}

package "domain.model" {
  class SuscripcionEntity
}

package "infrastructure.persistence" {
  class SuscripcionRepository
}

package "shared.exception" {
  class GlobalException
}

package "config" {
  class AppConfig
}

SuscripcionesController --> SuscripcionesService
SuscripcionesController --> SuscripcionDto

SuscripcionesService --> SuscripcionDto
SuscripcionesService --> SuscripcionMapper
SuscripcionesService --> SuscripcionEntity
SuscripcionesService --> SuscripcionRepository
SuscripcionesService --> GlobalException

SuscripcionMapper --> SuscripcionDto
SuscripcionMapper --> SuscripcionEntity

SuscripcionRepository --> SuscripcionEntity

@enduml