@startuml
!define C4P https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master
!includeurl C4P/C4_Container.puml

title Toget - C2 Diagrama de Contenedores

Person(provedor, "Proveedor de Cuentas", "")
Person(validador, "Validador de Cuentas", "")
Person(aPerfil, "Administrador de Perfiles", "")
Person(personalPagos, "Personal de Pagos", "")
Person(atencion, "Personal de Atención", "")
Person(usuario, "Usuario", "")

System_Boundary(toget, "Toget") {
    Container(webAppClientes, "App Web", "React/Vue", "Interfaz web para usuarios")
    Container(movilAppClientes, "Movil App", "React Native/Kotlin", "Interfaz web para usuarios")
    Container(webAppAdmin, "App Web Gestión", "React/Angular", "Interfaz web para el personal operativo")
    Container(apiGatewayBackOffice, "API Gateway Back Office", "Spring Cloud Gateway / Kong","Punto de entrada único a los servicios para el personal")
    Container(apiGatewayFrontOffice, "API Gateway Front Office", "Spring Cloud Gateway / Kong","Punto de entrada único a los servicios para el cliente")
    Container(msMarketing, "ms-marketing", "NestJS", "Gestiona promociones, campañas y notificaciones")
    Container(msSuscripciones, "ms-gestion-suscripciones", "NestJS", "Gestiona usuarios, suscripciones, vigencias y renovaciones")
    Container(msPlataformas, "ms-gestion-plataformas", "NestJS", "Gestiona plataformas de streaming, cuentas, perfiles y asignaciones")
    Container(msPagos, "ms-pagos", "NestJS", "Gestiona pagos y confirmaciones de transacciones")
    ContainerDb(dbMarketing, "Marketing DB", "MongoDB/Dinamo BD", "Base de datos de marketing y campañas")
    ContainerDb(dbPromociones, "Promociones DB", "Redis/Memcached", "Base de datos de promociones y ofertas")
    ContainerDb(dbSuscripciones, "Suscripciones DB", "PostgreSQL/EDB", "Base de datos de usuarios y suscripciones")
    ContainerDb(dbPlataformas, "Plataformas DB", "PostgreSQL/EDB", "Base de datos de plataformas, cuentas y perfiles")
    ContainerDb(dbPagos, "Pagos DB", "PostgreSQL/EDB", "Base de datos de pagos y transacciones")
}

System_Ext(whatsapp,"WhatsApp","")
System_Ext(correo, "Correo Electrónico", "")
System_Ext(paymentGateway,"Pasarela de Pagos", "")

' Relaciones usuarios
Rel(provedor, webAppAdmin, "Registra cuentas")
Rel(validador, webAppAdmin, "Valida cuentas y gestiona precios")
Rel(aPerfil, webAppAdmin, "Administra perfiles")
Rel(personalPagos, webAppAdmin, "Valida pagos y activa suscripciones")
Rel(atencion, webAppAdmin, "Gestiona incidencias")
Rel(usuario, webAppClientes, "Consulta servicios y gestiona sus suscripciones")
Rel(usuario, movilAppClientes, "Consulta servicios y gestiona sus suscripciones")

' Web → Gateway Front Office y Back Office
Rel(webAppClientes, apiGatewayFrontOffice, "Consume API REST", "HTTPS/JSON")
Rel(movilAppClientes, apiGatewayFrontOffice, "Consume API REST", "HTTPS/JSON")
Rel(webAppAdmin, apiGatewayBackOffice, "Consume API REST", "HTTPS/JSON")

' Gateway → Microservicios
Rel(apiGatewayFrontOffice, msMarketing, "Rutea")
Rel(apiGatewayFrontOffice, msSuscripciones, "Rutea")
Rel(apiGatewayBackOffice, msPlataformas, "Rutea")
Rel(apiGatewayBackOffice, msPagos, "Rutea")

' Microservicios → DB
Rel(msSuscripciones, dbSuscripciones, "Lee/Escribe")
Rel(msPlataformas, dbPlataformas, "Lee/Escribe")
Rel(msPagos, dbPagos, "Lee/Escribe")
Rel(msMarketing, dbPromociones, "Lee/Escribe(Cache)")
Rel(msMarketing, dbMarketing, "Lee/Escribe")
Rel(msMarketing, dbSuscripciones, "Consume información de usuarios")
Rel(msMarketing, dbPlataformas, "Consume información de plataformas")

' Integraciones externas
Rel(msMarketing, whatsapp, "Envía promociones y notificaciones")
Rel(msPlataformas, correo, "Envía credenciales y perfiles asignados")
Rel(msPagos, paymentGateway, "Procesa pagos")

SHOW_LEGEND()
@enduml