@startuml
skinparam classAttributeIconSize 0
class "GenericDomain"
class "RecordStatus"
class "StateErrorMessages"
class "RuntimeException"
class "DomainException"
class "DomainId"
class "ID"
class "Persona"
class "nombres"
class "ID"
class "Usuario"
class "Specialty"
class "UsuarioID"
class "Correo electronico"
class "DoctorSchedule"
class "DoctorException"
class "GenericEvent"
class "Suscripcion"
class "Pago"
class "Plataforma"
class "Cuenta"
class "Perfil"
class "Telefono"
"GenericDomain" --> "RecordStatus"
"GenericDomain" --> "DomainException"
"GenericDomain" --> "ID"
"GenericDomain" --> "DomainId"
"GenericDomain" --> "GenericEvent"
"RecordStatus" --> "StateErrorMessages"
"RuntimeException" <|-- "DomainException"
"DomainId" <|-- "ID"
"GenericDomain" <|-- "Persona"
"Persona" --> "nombres"
"Persona" --> "ID"
"Usuario" --> "Specialty"
"Persona" <|-- "Usuario"
"Usuario" --> "UsuarioID"
"Usuario" --> "Correo electronico"
"GenericDomain" <|-- "Usuario"
"Usuario" --> "DoctorException"
"Usuario" --> "ID"
"Usuario" --> "Suscripcion"
"DomainId" <|-- "UsuarioID"
"Correo electronico" --> "Persona"
"DoctorSchedule" --> "UsuarioID"
"DomainException" <|-- "DoctorException"
"Suscripcion" --> "Pago"
"Suscripcion" --> "Plataforma"
"Suscripcion" --> "Cuenta"
"Suscripcion" --> "Perfil"
"Cuenta" --> "Perfil"
"Telefono" --> "Persona"
@enduml